export const JOBS_DATA = [
  {
    id: 1,
    title: 'Développeur Full-Stack React/Node',
    company: 'Sopra Steria',
    location: 'Paris 15e',
    mode: 'Hybride',
    type: 'Alternance',
    duration: '24 mois',
    description: 'Rejoignez une équipe agile pour concevoir et développer des applications web modernes. Stack : React, Node.js, PostgreSQL, Docker.',
    skills: ['React', 'Node.js', 'SQL', 'Git'],
    posted: 'Il y a 2 jours',
  },
  {
    id: 2,
    title: 'Développeur Mobile Flutter',
    company: 'BlaBlaCar',
    location: 'Paris 8e',
    mode: 'Présentiel',
    type: 'Stage',
    duration: '6 mois',
    description: 'Participez au développement de l\'application mobile utilisée par des millions d\'utilisateurs. Fonctionnalités passager et conducteur.',
    skills: ['Flutter', 'Dart', 'Firebase', 'REST API'],
    posted: 'Il y a 3 jours',
  },
  {
    id: 3,
    title: 'Data Engineer Junior',
    company: 'Deezer',
    location: 'Paris 11e',
    mode: 'Hybride',
    type: 'Alternance',
    duration: '12 mois',
    description: 'Construire et maintenir nos pipelines de données pour analyser les comportements d\'écoute de nos 9 millions d\'utilisateurs actifs.',
    skills: ['Python', 'Spark', 'Airflow', 'SQL'],
    posted: 'Il y a 5 jours',
  },
  {
    id: 4,
    title: 'Ingénieur DevOps',
    company: 'OVHcloud',
    location: 'Roubaix',
    mode: 'Full remote',
    type: 'Stage',
    duration: '4 à 6 mois',
    description: 'Automatisez nos processus CI/CD et participez à la fiabilisation de notre infrastructure cloud européenne.',
    skills: ['Kubernetes', 'Terraform', 'Ansible', 'Linux'],
    posted: 'Il y a 1 semaine',
  },
  {
    id: 5,
    title: 'UX/UI Designer & Développeur Front',
    company: 'Doctolib',
    location: 'Paris 9e',
    mode: 'Hybride',
    type: 'Alternance',
    duration: '24 mois',
    description: 'Contribuez à l\'amélioration de l\'expérience patient et praticien sur notre plateforme de santé numérique.',
    skills: ['Figma', 'React', 'TypeScript', 'CSS'],
    posted: 'Il y a 1 semaine',
  },
  {
    id: 6,
    title: 'Développeur Backend Python',
    company: 'Ledger',
    location: 'Paris 10e',
    mode: 'Hybride',
    type: 'Stage',
    duration: '6 mois',
    description: 'Travaillez sur des solutions de sécurité pour les crypto-actifs. Développement d\'APIs et microservices robustes.',
    skills: ['Python', 'FastAPI', 'PostgreSQL', 'Blockchain'],
    posted: 'Il y a 2 semaines',
  },
  {
    id: 7,
    title: 'Développeur React Native',
    company: 'Qonto',
    location: 'Lyon',
    mode: 'Hybride',
    type: 'Alternance',
    duration: '12 mois',
    description: 'Contribuez à l\'application mobile de la néobanque des entrepreneurs et PME européens.',
    skills: ['React Native', 'TypeScript', 'Redux', 'Jest'],
    posted: 'Il y a 3 jours',
  },
  {
    id: 8,
    title: 'Administrateur Système & Réseau',
    company: 'Thales',
    location: 'Bordeaux',
    mode: 'Présentiel',
    type: 'Stage',
    duration: '6 mois',
    description: 'Administration des infrastructures réseau et système dans un contexte de cybersécurité industrielle.',
    skills: ['Linux', 'Cisco', 'VMware', 'Firewall'],
    posted: 'Il y a 4 jours',
  },
];
